### ISSUE TITLE
How to change the tintColor?

### ISSUE THREAD

**Issue by changelee82** [nesium/SVG#1]
[ic_first_white.svg.zip](https://github.com/nesium/SVG/files/3723775/ic_first_white.svg.zip)

![svg](https://user-images.githubusercontent.com/13742589/66741631-88e2eb80-eea8-11e9-9076-600a2a0e8091.jpg)
I want to change the tintColor of this image. I try to change fillColor or strokeColor, but display error.
![svg2](https://user-images.githubusercontent.com/13742589/66742117-85039900-eea9-11e9-92f7-d32ef1ee85c5.jpg)
![svg3](https://user-images.githubusercontent.com/13742589/66742185-b11f1a00-eea9-11e9-8fa5-88b2e8d002b7.jpg)

**Comment by nesium** [comment]
You have two paths in your SVG. If you override the fillColor globally that path gets filled as well and you cannot see your triangle anymore. The easiest solution would be to remove that path.

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path d="M12 7.77L18.39 18H5.61L12 7.77M12 4L2 20h20L12 4z"/>
    <!-- Remove this -> <path fill="none" d="M0 0h24v24H0V0z"/> -->
</svg>
``` 

The other option is to assign an `id` to your triangle and override the style selectively. This can be seen [here](https://github.com/nesium/SVG/blob/83c83c8c861d41672ed655daf27a0947f0571738/Tests/SVGTests/ImageRendererTests.swift#L95). The input SVG is [here](https://raw.githubusercontent.com/nesium/SVG/master/Tests/SVGTests/Fixtures/badge.svg) and [this](https://github.com/nesium/SVG/blob/master/Tests/SVGTests/__Snapshots__/ImageRendererTests/testColorElementsWithStyleOverride.1.png) is the result.

**Comment by changelee82** [comment]
Thank you for your patience.
